# Generated by Django 2.2.14 on 2020-11-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='autor',
            name='correo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
