# Generated by Django 2.2.14 on 2020-11-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros', to='autores.Autor'),
        ),
    ]
