# Generated by Django 2.2.14 on 2020-11-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editoriales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
    ]
